name: tor homepage
description: tor homepage description
menu:
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Teaching
   url: /teaching
menu_external:
 - title: Github
   url: "https://github.com/tttor"
 - title: GoogleScholar
   url: "https://scholar.google.com/citations?user=AYOBcPYAAAAJ"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl:
locale: en_GB
