name: Vektor Dewanto
description: tor homepage description
menu:
 - page: Home
   url: /index
 - page: Robots
   url: /robot
 - page: Projects
   url: /project
 - page: Islam
   url: /islam
 - page: Family
   url: /family
 - page: Indonesia+Jawa
   url: /idjv
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl:
locale: en_GB
