name: Vektor Dewanto
description: tor homepage description
menu:
 - page: Home
   url: /index
 - page: Research
   url: /research
 - page: Islam
   url: /islam
 - page: Family
   url: /family
 - page: Resources
   url: /resource
 - page: Links
   url: /link
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl:
locale: en_GB
