name: Vektor Dewanto
description: tor homepage description
menu:
 - page: Home
   url: /index
 - page: Robot
   url: /robot
 - page: Project
   url: /project
 - page: Personal
   url: /personal
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl:
locale: en_GB
